import type { Shop } from "@/components/shared/ShopCard";

/**
 * Demo fallback shops — used ONLY when there is no real salon data in the
 * database yet. As soon as real salons exist they take over.
 */
export const DEMO_SHOPS: Shop[] = [
  {
    slug: "glow-studio-jaipur",
    name: "Glow Studio",
    tagline: "Premium unisex salon in C-Scheme",
    category: "Unisex Salon",
    area: "C-Scheme",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
    rating: 4.8,
    review_count: 342,
    is_verified: true,
    starting_price: 299,
    popularity: 342,
    gender: "unisex",
    price_level: 2,
    distance_km: 1.2,
    membership_perk: null,
    badges: ["verified", "top_rated"],
  },
  {
    slug: "serene-spa-wellness",
    name: "Serene Spa & Wellness",
    tagline: "Ayurvedic spa & wellness retreat",
    category: "Spa",
    area: "Malviya Nagar",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    rating: 4.9,
    review_count: 512,
    is_verified: true,
    starting_price: 799,
    popularity: 512,
    gender: "unisex",
    price_level: 3,
    distance_km: 2.4,
    membership_perk: null,
    badges: ["verified", "most_popular"],
  },
  {
    slug: "royal-barber-co",
    name: "Royal Barber Co.",
    tagline: "Classic men's grooming & beard care",
    category: "Barber Shop",
    area: "Raja Park",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80",
    rating: 4.7,
    review_count: 220,
    is_verified: true,
    starting_price: 199,
    popularity: 220,
    gender: "male",
    price_level: 1,
    distance_km: 3.1,
    membership_perk: null,
    badges: ["verified"],
  },
  {
    slug: "nail-aura-studio",
    name: "Nail Aura Studio",
    tagline: "Nail art, gel & extensions",
    category: "Nail Studio",
    area: "Vaishali Nagar",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
    rating: 4.8,
    review_count: 188,
    is_verified: false,
    starting_price: 499,
    popularity: 188,
    gender: "female",
    price_level: 2,
    distance_km: 4.5,
    membership_perk: null,
    badges: ["top_rated"],
  },
  {
    slug: "inkline-tattoo-studio",
    name: "Inkline Tattoo Studio",
    tagline: "Custom & small tattoos by certified artists",
    category: "Tattoo Studio",
    area: "Mansarovar",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=800&q=80",
    rating: 4.9,
    review_count: 96,
    is_verified: true,
    starting_price: 999,
    popularity: 96,
    gender: "unisex",
    price_level: 3,
    distance_km: 5.2,
    membership_perk: null,
    badges: ["verified"],
  },
  {
    slug: "bridal-glow-makeup",
    name: "Bridal Glow Makeup",
    tagline: "Party & bridal makeup specialists",
    category: "Beauty Salon",
    area: "Jagatpura",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    rating: 4.8,
    review_count: 275,
    is_verified: false,
    starting_price: 1499,
    popularity: 275,
    gender: "female",
    price_level: 4,
    distance_km: 6.0,
    membership_perk: null,
    badges: ["most_popular"],
  },
  {
    slug: "urban-hair-lounge",
    name: "Urban Hair Lounge",
    tagline: "Modern cuts, colour & hair spa",
    category: "Hair Salon",
    area: "Tonk Road",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80",
    rating: 4.6,
    review_count: 410,
    is_verified: true,
    starting_price: 349,
    popularity: 410,
    gender: "unisex",
    price_level: 2,
    distance_km: 2.8,
    membership_perk: null,
    badges: ["verified"],
  },
  {
    slug: "harmony-massage-center",
    name: "Harmony Massage Center",
    tagline: "Therapeutic massage & relaxation",
    category: "Massage Center",
    area: "Bani Park",
    city: "Jaipur",
    cover_image:
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80",
    rating: 4.7,
    review_count: 134,
    is_verified: true,
    starting_price: 699,
    popularity: 134,
    gender: "unisex",
    price_level: 2,
    distance_km: 3.6,
    membership_perk: null,
    badges: ["verified"],
  },
];
