// Mock India geographical hierarchy: State -> Districts -> Blocks (tehsils).
// Comprehensive list of all 28 states + 8 UTs. Districts cover the major
// official districts per state; blocks are a representative set per district.
// Replace with a server-driven source when an official API becomes available.

export type GeoTree = Record<string, Record<string, string[]>>;

const b = (...names: string[]) => names;

export const INDIA_GEO: GeoTree = {
  "Andhra Pradesh": {
    Anantapur: b("Anantapur", "Dharmavaram", "Kadiri", "Hindupur", "Penukonda"),
    Chittoor: b("Chittoor", "Tirupati", "Madanapalle", "Punganur", "Palamaner"),
    "East Godavari": b("Kakinada", "Rajahmundry", "Amalapuram", "Peddapuram"),
    Guntur: b("Guntur", "Tenali", "Bapatla", "Narasaraopet"),
    Krishna: b("Vijayawada", "Machilipatnam", "Gudivada", "Nuzvid"),
    Kurnool: b("Kurnool", "Nandyal", "Adoni", "Yemmiganur"),
    Nellore: b("Nellore", "Gudur", "Kavali", "Atmakur"),
    Prakasam: b("Ongole", "Markapur", "Kandukur", "Chirala"),
    Srikakulam: b("Srikakulam", "Tekkali", "Palasa", "Amadalavalasa"),
    Visakhapatnam: b("Visakhapatnam", "Anakapalle", "Bheemunipatnam", "Paderu"),
    Vizianagaram: b("Vizianagaram", "Parvathipuram", "Bobbili", "Salur"),
    "West Godavari": b("Eluru", "Bhimavaram", "Tadepalligudem", "Tanuku"),
    "YSR Kadapa": b("Kadapa", "Proddatur", "Rayachoti", "Pulivendula"),
  },
  "Arunachal Pradesh": {
    Tawang: b("Tawang", "Lumla", "Jang"),
    "West Kameng": b("Bomdila", "Dirang", "Kalaktang"),
    "East Kameng": b("Seppa", "Chayang Tajo"),
    "Papum Pare": b("Yupia", "Doimukh", "Sagalee"),
    "Lower Subansiri": b("Ziro", "Yachuli"),
    "Upper Subansiri": b("Daporijo", "Dumporijo"),
    "West Siang": b("Aalo", "Basar"),
    "East Siang": b("Pasighat", "Mebo"),
    Changlang: b("Changlang", "Miao", "Bordumsa"),
    Tirap: b("Khonsa", "Deomali"),
  },
  Assam: {
    "Kamrup Metropolitan": b("Guwahati", "Dispur", "Sonapur", "Azara"),
    Kamrup: b("Amingaon", "Rangia", "Hajo", "Boko"),
    Dibrugarh: b("Dibrugarh", "Naharkatia", "Tingkhong", "Tengakhat"),
    Cachar: b("Silchar", "Sonai", "Lakhipur", "Udharbond"),
    Nagaon: b("Nagaon", "Kaliabor", "Raha", "Dhing"),
    Sonitpur: b("Tezpur", "Dhekiajuli", "Rangapara", "Biswanath"),
    Jorhat: b("Jorhat", "Titabar", "Mariani"),
    Sivasagar: b("Sivasagar", "Nazira", "Amguri"),
    Tinsukia: b("Tinsukia", "Margherita", "Doomdooma"),
    Barpeta: b("Barpeta", "Sarthebari", "Sarukhetri"),
  },
  Bihar: {
    Patna: b("Patna Sadar", "Danapur", "Barh", "Masaurhi", "Paliganj"),
    Gaya: b("Gaya", "Bodh Gaya", "Tikari", "Sherghati"),
    Bhagalpur: b("Bhagalpur", "Sultanganj", "Naugachhia", "Kahalgaon"),
    Muzaffarpur: b("Muzaffarpur", "Bochaha", "Kanti", "Sakra"),
    Darbhanga: b("Darbhanga", "Benipur", "Biraul"),
    Purnia: b("Purnia East", "Banmankhi", "Dhamdaha"),
    Begusarai: b("Begusarai", "Teghra", "Bachhwara", "Manjhaul"),
    Nalanda: b("Bihar Sharif", "Hilsa", "Rajgir", "Asthawan"),
    Saran: b("Chhapra", "Sonpur", "Marhaura"),
    "East Champaran": b("Motihari", "Adapur", "Areraj"),
    "West Champaran": b("Bettiah", "Bagaha", "Narkatiaganj"),
    Vaishali: b("Hajipur", "Mahnar", "Lalganj"),
  },
  Chhattisgarh: {
    Raipur: b("Raipur", "Arang", "Abhanpur", "Tilda"),
    Bilaspur: b("Bilaspur", "Kota", "Takhatpur", "Bilha"),
    Durg: b("Durg", "Bhilai", "Patan"),
    Korba: b("Korba", "Katghora", "Pali"),
    Raigarh: b("Raigarh", "Kharsia", "Sarangarh"),
    Bastar: b("Jagdalpur", "Bastar", "Tokapal"),
    Rajnandgaon: b("Rajnandgaon", "Dongargarh", "Khairagarh"),
    "Janjgir-Champa": b("Janjgir", "Champa", "Akaltara"),
  },
  Goa: {
    "North Goa": b("Panaji", "Mapusa", "Bicholim", "Pernem", "Bardez"),
    "South Goa": b("Margao", "Vasco da Gama", "Quepem", "Canacona", "Ponda"),
  },
  Gujarat: {
    Ahmedabad: b("Ahmedabad City", "Daskroi", "Sanand", "Dholka", "Bavla"),
    Surat: b("Surat City", "Choryasi", "Olpad", "Bardoli"),
    Vadodara: b("Vadodara", "Padra", "Karjan", "Savli"),
    Rajkot: b("Rajkot", "Gondal", "Jasdan", "Jetpur"),
    Bhavnagar: b("Bhavnagar", "Sihor", "Mahuva", "Palitana"),
    Jamnagar: b("Jamnagar", "Dhrol", "Kalavad", "Lalpur"),
    Junagadh: b("Junagadh", "Visavadar", "Manavadar", "Keshod"),
    Gandhinagar: b("Gandhinagar", "Kalol", "Mansa", "Dehgam"),
    Anand: b("Anand", "Petlad", "Borsad", "Khambhat"),
    Kheda: b("Nadiad", "Mahudha", "Kapadvanj", "Thasra"),
    Mehsana: b("Mehsana", "Visnagar", "Vijapur", "Unjha"),
    Kutch: b("Bhuj", "Anjar", "Gandhidham", "Mandvi", "Mundra"),
  },
  Haryana: {
    Gurugram: b("Gurugram", "Sohna", "Pataudi", "Farukhnagar", "Manesar"),
    Faridabad: b("Faridabad", "Ballabgarh", "Tigaon"),
    Hisar: b("Hisar", "Hansi", "Adampur", "Barwala"),
    Karnal: b("Karnal", "Gharaunda", "Indri", "Nilokheri"),
    Panipat: b("Panipat", "Samalkha", "Israna", "Bapoli"),
    Sonipat: b("Sonipat", "Ganaur", "Gohana", "Kharkhoda"),
    Ambala: b("Ambala City", "Ambala Cantt", "Naraingarh", "Barara"),
    Rohtak: b("Rohtak", "Meham", "Sampla", "Kalanaur"),
    Yamunanagar: b("Yamunanagar", "Jagadhri", "Bilaspur", "Chhachhrauli"),
    Kurukshetra: b("Thanesar", "Pehowa", "Shahabad", "Ladwa"),
  },
  "Himachal Pradesh": {
    Shimla: b("Shimla Urban", "Shimla Rural", "Rohru", "Theog", "Rampur"),
    Kangra: b("Dharamshala", "Palampur", "Nurpur", "Dehra", "Jawali"),
    Mandi: b("Mandi Sadar", "Sundernagar", "Sarkaghat", "Joginder Nagar"),
    Kullu: b("Kullu", "Manali", "Banjar", "Ani"),
    Solan: b("Solan", "Nalagarh", "Arki", "Kasauli"),
    Hamirpur: b("Hamirpur", "Barsar", "Sujanpur", "Nadaun"),
    Una: b("Una", "Amb", "Haroli", "Bangana"),
    Bilaspur: b("Bilaspur Sadar", "Ghumarwin", "Jhandutta"),
    Chamba: b("Chamba", "Dalhousie", "Bharmour", "Pangi"),
    Sirmaur: b("Nahan", "Paonta Sahib", "Rajgarh", "Sangrah"),
    Kinnaur: b("Kalpa", "Nichar", "Pooh"),
    "Lahaul and Spiti": b("Keylong", "Kaza", "Udaipur"),
  },
  Jharkhand: {
    Ranchi: b("Ranchi Sadar", "Bundu", "Tamar", "Khelari"),
    Dhanbad: b("Dhanbad", "Baghmara", "Govindpur", "Nirsa"),
    "East Singhbhum": b("Jamshedpur", "Ghatshila", "Potka", "Patamda"),
    "West Singhbhum": b("Chaibasa", "Jagannathpur", "Manoharpur"),
    Bokaro: b("Bokaro", "Chas", "Chandankiyari", "Bermo"),
    Hazaribagh: b("Hazaribagh", "Barhi", "Barkagaon", "Ichak"),
    Giridih: b("Giridih", "Bagodar", "Dumri", "Tisri"),
    Deoghar: b("Deoghar", "Madhupur", "Sarath", "Mohanpur"),
  },
  Karnataka: {
    "Bengaluru Urban": b(
      "Bengaluru North",
      "Bengaluru South",
      "Bengaluru East",
      "Anekal",
      "Yelahanka",
    ),
    "Bengaluru Rural": b("Devanahalli", "Doddaballapur", "Hosakote", "Nelamangala"),
    Mysuru: b("Mysuru", "Nanjangud", "T. Narsipur", "Hunsur", "K.R. Nagar"),
    "Mangaluru (Dakshina Kannada)": b("Mangaluru", "Bantwal", "Puttur", "Sullia", "Belthangady"),
    Belagavi: b("Belagavi", "Chikodi", "Gokak", "Athani", "Bailhongal"),
    "Hubballi-Dharwad": b("Hubballi", "Dharwad", "Kalghatgi", "Navalgund"),
    Tumakuru: b("Tumakuru", "Tiptur", "Sira", "Madhugiri", "Pavagada"),
    Shivamogga: b("Shivamogga", "Bhadravati", "Sagara", "Thirthahalli"),
    Davanagere: b("Davanagere", "Harihar", "Channagiri", "Honnali"),
    Ballari: b("Ballari", "Hospet", "Siruguppa", "Sandur"),
    Kalaburagi: b("Kalaburagi", "Aland", "Chittapur", "Sedam"),
    Vijayapura: b("Vijayapura", "Indi", "Sindgi", "Basavana Bagewadi"),
    Udupi: b("Udupi", "Karkala", "Kundapura", "Brahmavar"),
    Hassan: b("Hassan", "Arsikere", "Channarayapatna", "Holenarsipur"),
    Mandya: b("Mandya", "Maddur", "Malavalli", "Pandavapura"),
  },
  Kerala: {
    Thiruvananthapuram: b("Thiruvananthapuram", "Neyyattinkara", "Nedumangad", "Chirayinkeezhu"),
    Kollam: b("Kollam", "Karunagappally", "Punalur", "Kottarakkara"),
    Pathanamthitta: b("Pathanamthitta", "Adoor", "Tiruvalla", "Mallappally"),
    Alappuzha: b("Alappuzha", "Cherthala", "Kayamkulam", "Mavelikkara"),
    Kottayam: b("Kottayam", "Changanassery", "Vaikom", "Meenachil"),
    Idukki: b("Painavu", "Devikulam", "Udumbanchola", "Thodupuzha"),
    Ernakulam: b("Kochi", "Aluva", "Muvattupuzha", "Perumbavoor", "Kothamangalam"),
    Thrissur: b("Thrissur", "Chalakudy", "Irinjalakuda", "Kodungallur", "Mukundapuram"),
    Palakkad: b("Palakkad", "Ottapalam", "Chittur", "Mannarkkad", "Alathur"),
    Malappuram: b("Malappuram", "Manjeri", "Tirur", "Ponnani", "Nilambur"),
    Kozhikode: b("Kozhikode", "Vatakara", "Koyilandy", "Thamarassery"),
    Wayanad: b("Kalpetta", "Mananthavady", "Sulthan Bathery", "Vythiri"),
    Kannur: b("Kannur", "Thalassery", "Taliparamba", "Iritty"),
    Kasaragod: b("Kasaragod", "Kanhangad", "Hosdurg", "Manjeshwar"),
  },
  "Madhya Pradesh": {
    Bhopal: b("Bhopal", "Berasia", "Huzur"),
    Indore: b("Indore", "Mhow", "Depalpur", "Sanwer"),
    Jabalpur: b("Jabalpur", "Sihora", "Patan", "Kundam"),
    Gwalior: b("Gwalior", "Dabra", "Bhitarwar"),
    Ujjain: b("Ujjain", "Mahidpur", "Khachrod", "Tarana"),
    Sagar: b("Sagar", "Khurai", "Bina", "Rehli"),
    Rewa: b("Rewa", "Mauganj", "Sirmour", "Teonthar"),
    Satna: b("Satna", "Maihar", "Nagod", "Amarpatan"),
    Ratlam: b("Ratlam", "Jaora", "Sailana", "Alot"),
    Dewas: b("Dewas", "Sonkatch", "Bagli", "Kannod"),
    Chhindwara: b("Chhindwara", "Parasia", "Pandhurna", "Sausar"),
    Khargone: b("Khargone", "Bhikangaon", "Maheshwar", "Kasrawad"),
  },
  Maharashtra: {
    "Mumbai City": b("Colaba", "Byculla", "Mazgaon", "Worli"),
    "Mumbai Suburban": b("Andheri", "Borivali", "Kurla", "Bandra", "Goregaon"),
    Pune: b("Pune City", "Haveli", "Mulshi", "Maval", "Khed", "Junnar"),
    Thane: b("Thane", "Kalyan", "Bhiwandi", "Murbad", "Shahapur"),
    Nagpur: b("Nagpur Urban", "Nagpur Rural", "Hingna", "Kamptee", "Umred"),
    Nashik: b("Nashik", "Malegaon", "Sinnar", "Niphad", "Dindori"),
    "Aurangabad (Chhatrapati Sambhajinagar)": b("Aurangabad", "Vaijapur", "Gangapur", "Sillod"),
    Solapur: b("Solapur North", "Solapur South", "Pandharpur", "Barshi", "Akkalkot"),
    Kolhapur: b("Kolhapur", "Karveer", "Hatkanangle", "Shirol", "Panhala"),
    Satara: b("Satara", "Karad", "Wai", "Phaltan", "Patan"),
    Sangli: b("Sangli", "Miraj", "Tasgaon", "Walwa", "Jat"),
    Ahmednagar: b("Ahmednagar", "Shrirampur", "Sangamner", "Kopargaon", "Rahuri"),
    Raigad: b("Alibag", "Panvel", "Pen", "Khalapur", "Mahad"),
    Ratnagiri: b("Ratnagiri", "Chiplun", "Khed", "Dapoli", "Guhagar"),
    Palghar: b("Palghar", "Vasai", "Dahanu", "Jawhar", "Wada"),
  },
  Manipur: {
    "Imphal East": b("Imphal East-I", "Imphal East-II", "Sawombung"),
    "Imphal West": b("Imphal West-I", "Imphal West-II", "Lamshang"),
    Thoubal: b("Thoubal", "Lilong", "Kakching"),
    Bishnupur: b("Bishnupur", "Nambol", "Moirang"),
    Churachandpur: b("Churachandpur", "Henglep", "Singngat"),
    Senapati: b("Senapati", "Kangpokpi", "Saitu Gamphazol"),
    Tamenglong: b("Tamenglong", "Tousem", "Nungba"),
    Ukhrul: b("Ukhrul", "Phungyar", "Kasom Khullen"),
    Chandel: b("Chandel", "Tengnoupal", "Machi"),
  },
  Meghalaya: {
    "East Khasi Hills": b("Shillong", "Mawkynrew", "Mawphlang", "Pynursla"),
    "West Khasi Hills": b("Nongstoin", "Mairang", "Mawthadraishan"),
    "Ri Bhoi": b("Nongpoh", "Umsning", "Jirang"),
    "East Garo Hills": b("Williamnagar", "Songsak", "Samanda"),
    "West Garo Hills": b("Tura", "Dadenggre", "Selsella"),
    "South Garo Hills": b("Baghmara", "Chokpot", "Rongara"),
    "Jaintia Hills (East)": b("Khliehriat", "Saipung", "Sutnga"),
    "Jaintia Hills (West)": b("Jowai", "Amlarem", "Thadlaskein"),
  },
  Mizoram: {
    Aizawl: b("Aizawl North", "Aizawl South", "Aizawl East", "Aizawl West"),
    Lunglei: b("Lunglei", "Hnahthial", "Tlabung"),
    Champhai: b("Champhai", "Khawzawl", "Khawbung"),
    Kolasib: b("Kolasib", "Bilkhawthlir", "Vairengte"),
    Serchhip: b("Serchhip", "Thenzawl", "North Vanlaiphai"),
    Mamit: b("Mamit", "West Phaileng", "Reiek"),
    Lawngtlai: b("Lawngtlai", "Chawngte", "Bungtlang South"),
    Saiha: b("Saiha", "Tuipang"),
  },
  Nagaland: {
    Kohima: b("Kohima Sadar", "Sechu Zubza", "Tseminyu", "Chiephobozou"),
    Dimapur: b("Dimapur Sadar", "Niuland", "Medziphema", "Dhansiripar"),
    Mokokchung: b("Mokokchung Sadar", "Tuli", "Changtongya", "Mangkolemba"),
    Tuensang: b("Tuensang Sadar", "Noksen", "Sangsangnyu"),
    Mon: b("Mon Sadar", "Aboi", "Wakching", "Tobu"),
    Wokha: b("Wokha Sadar", "Bhandari", "Sanis"),
    Zunheboto: b("Zunheboto Sadar", "Pughoboto", "Aghunato"),
    Phek: b("Phek Sadar", "Pfutsero", "Meluri"),
    Kiphire: b("Kiphire Sadar", "Pungro", "Seyochung"),
    Longleng: b("Longleng Sadar", "Tamlu"),
    Peren: b("Peren Sadar", "Jalukie", "Tening"),
  },
  Odisha: {
    Khordha: b("Bhubaneswar", "Khordha", "Jatni", "Balianta"),
    Cuttack: b("Cuttack Sadar", "Salepur", "Athagarh", "Banki"),
    Ganjam: b("Berhampur", "Chhatrapur", "Aska", "Bhanjanagar"),
    Puri: b("Puri Sadar", "Pipili", "Nimapara", "Konark"),
    Sambalpur: b("Sambalpur", "Bamra", "Kuchinda", "Rairakhol"),
    Sundargarh: b("Sundargarh", "Rourkela", "Bonai", "Panposh"),
    Balasore: b("Balasore", "Nilagiri", "Soro", "Basta"),
    Mayurbhanj: b("Baripada", "Karanjia", "Rairangpur", "Bangiriposi"),
    Koraput: b("Koraput", "Jeypore", "Sunabeda", "Kotpad"),
    Kalahandi: b("Bhawanipatna", "Dharmagarh", "Junagarh", "Madanpur Rampur"),
  },
  Punjab: {
    Ludhiana: b("Ludhiana East", "Ludhiana West", "Khanna", "Samrala", "Jagraon"),
    Amritsar: b("Amritsar I", "Amritsar II", "Ajnala", "Baba Bakala"),
    Jalandhar: b("Jalandhar I", "Jalandhar II", "Phillaur", "Nakodar", "Shahkot"),
    Patiala: b("Patiala", "Nabha", "Rajpura", "Samana", "Dudhansadhan"),
    "Mohali (SAS Nagar)": b("Mohali", "Kharar", "Derabassi"),
    Bathinda: b("Bathinda", "Talwandi Sabo", "Rampura Phul", "Maur"),
    Hoshiarpur: b("Hoshiarpur I", "Hoshiarpur II", "Garhshankar", "Dasuya", "Mukerian"),
    Ferozepur: b("Ferozepur", "Zira", "Guru Har Sahai"),
    Gurdaspur: b("Gurdaspur", "Batala", "Dera Baba Nanak", "Dinanagar"),
    Sangrur: b("Sangrur", "Dhuri", "Malerkotla", "Sunam"),
  },
  Rajasthan: {
    Jaipur: b("Jaipur", "Amer", "Sanganer", "Bassi", "Chaksu", "Phagi"),
    Jodhpur: b("Jodhpur", "Phalodi", "Osian", "Bilara", "Shergarh"),
    Udaipur: b("Udaipur", "Girwa", "Mavli", "Salumber", "Kherwara"),
    Kota: b("Kota", "Ladpura", "Ramganj Mandi", "Sangod", "Pipalda"),
    Ajmer: b("Ajmer", "Kishangarh", "Beawar", "Kekri", "Nasirabad"),
    Bikaner: b("Bikaner", "Nokha", "Lunkaransar", "Kolayat"),
    Alwar: b("Alwar", "Behror", "Bansur", "Tijara", "Mundawar"),
    Bharatpur: b("Bharatpur", "Deeg", "Kumher", "Nadbai", "Bayana"),
    Sikar: b("Sikar", "Neem ka Thana", "Dantaramgarh", "Lachhmangarh"),
    Pali: b("Pali", "Sojat", "Bali", "Desuri", "Sumerpur"),
    Ganganagar: b("Sri Ganganagar", "Karanpur", "Padampur", "Suratgarh"),
    Barmer: b("Barmer", "Baytu", "Pachpadra", "Sheo", "Siwana"),
  },
  Sikkim: {
    "East Sikkim": b("Gangtok", "Pakyong", "Rongli", "Rakdong-Tintek"),
    "West Sikkim": b("Gyalshing", "Soreng", "Yuksom", "Dentam"),
    "North Sikkim": b("Mangan", "Chungthang", "Lachen", "Lachung"),
    "South Sikkim": b("Namchi", "Ravangla", "Yangang", "Jorethang"),
  },
  "Tamil Nadu": {
    Chennai: b("Egmore", "Mylapore", "Tondiarpet", "Perambur", "Anna Nagar"),
    Coimbatore: b("Coimbatore North", "Coimbatore South", "Mettupalayam", "Pollachi", "Sulur"),
    Madurai: b("Madurai North", "Madurai South", "Melur", "Vadipatti", "Usilampatti"),
    Tiruchirappalli: b("Tiruchirappalli", "Lalgudi", "Manapparai", "Musiri", "Thuraiyur"),
    Salem: b("Salem", "Attur", "Mettur", "Omalur", "Sankari"),
    Tirunelveli: b("Tirunelveli", "Ambasamudram", "Cheranmahadevi", "Nanguneri", "Palayamkottai"),
    Erode: b("Erode", "Bhavani", "Gobichettipalayam", "Sathyamangalam", "Perundurai"),
    Vellore: b("Vellore", "Katpadi", "Anaicut", "Gudiyatham"),
    Kanchipuram: b("Kanchipuram", "Walajabad", "Uthiramerur", "Sriperumbudur"),
    Thanjavur: b("Thanjavur", "Kumbakonam", "Pattukkottai", "Orathanadu", "Papanasam"),
    Tiruppur: b("Tiruppur North", "Tiruppur South", "Avinashi", "Palladam", "Dharapuram"),
    Dindigul: b("Dindigul", "Palani", "Kodaikanal", "Natham", "Vedasandur"),
  },
  Telangana: {
    Hyderabad: b("Charminar", "Secunderabad", "Khairatabad", "Bahadurpura", "Golconda"),
    Rangareddy: b("Rajendranagar", "Shamshabad", "Maheshwaram", "Ibrahimpatnam", "Chevella"),
    "Medchal-Malkajgiri": b("Medchal", "Malkajgiri", "Kapra", "Quthbullapur", "Shamirpet"),
    Sangareddy: b("Sangareddy", "Patancheru", "Zaheerabad", "Narayankhed"),
    Warangal: b("Warangal", "Hanamkonda", "Wardhannapet", "Khanapur"),
    Karimnagar: b("Karimnagar", "Huzurabad", "Jammikunta", "Choppadandi"),
    Khammam: b("Khammam Urban", "Khammam Rural", "Madhira", "Sathupalli"),
    Nalgonda: b("Nalgonda", "Miryalaguda", "Devarakonda", "Nakrekal"),
    Nizamabad: b("Nizamabad North", "Nizamabad South", "Armoor", "Bodhan"),
    Mahbubnagar: b("Mahbubnagar", "Jadcherla", "Devarkadra", "Bhoothpur"),
  },
  Tripura: {
    "West Tripura": b("Agartala", "Mohanpur", "Bamutia", "Jirania"),
    Sepahijala: b("Bishalgarh", "Sonamura", "Melaghar", "Boxanagar"),
    Khowai: b("Khowai", "Teliamura", "Padmabil"),
    Gomati: b("Udaipur", "Amarpur", "Karbook", "Kakraban"),
    "South Tripura": b("Belonia", "Sabroom", "Santirbazar", "Hrishyamukh"),
    Dhalai: b("Ambassa", "Kamalpur", "Longtharai Valley", "Manu"),
    Unakoti: b("Kailasahar", "Kumarghat", "Gournagar"),
    "North Tripura": b("Dharmanagar", "Panisagar", "Damcherra", "Kadamtala"),
  },
  "Uttar Pradesh": {
    Lucknow: b("Lucknow", "Sarojini Nagar", "Mohanlalganj", "Bakshi Ka Talab", "Malihabad"),
    "Kanpur Nagar": b("Sadar", "Bilhaur", "Ghatampur", "Narwal"),
    Varanasi: b("Varanasi", "Pindra", "Cholapur", "Sevapuri"),
    Agra: b("Agra", "Etmadpur", "Bah", "Kheragarh", "Fatehabad"),
    Prayagraj: b("Sadar", "Soraon", "Phulpur", "Karchhana", "Bara", "Meja"),
    Meerut: b("Meerut", "Mawana", "Sardhana", "Daurala"),
    Ghaziabad: b("Ghaziabad", "Loni", "Modinagar", "Muradnagar"),
    "Gautam Buddha Nagar (Noida)": b("Dadri", "Sadar (Noida)", "Jewar"),
    Aligarh: b("Koil", "Atrauli", "Khair", "Iglas", "Gabhana"),
    Bareilly: b("Bareilly", "Aonla", "Faridpur", "Meerganj", "Nawabganj"),
    Moradabad: b("Moradabad", "Thakurdwara", "Bilari", "Kanth"),
    Saharanpur: b("Saharanpur", "Behat", "Deoband", "Nakur"),
    Gorakhpur: b("Sadar", "Sahjanwa", "Khajni", "Bansgaon", "Chauri-Chaura"),
    Ayodhya: b("Sadar", "Bikapur", "Milkipur", "Rudauli", "Sohawal"),
    Mathura: b("Mathura", "Mat", "Chhata", "Govardhan"),
    Jhansi: b("Jhansi", "Mauranipur", "Garautha", "Moth"),
  },
  Uttarakhand: {
    Dehradun: b("Dehradun", "Mussoorie", "Vikasnagar", "Chakrata", "Doiwala", "Rishikesh"),
    Haridwar: b("Haridwar", "Roorkee", "Laksar", "Bhagwanpur", "Narsan"),
    Nainital: b("Nainital", "Haldwani", "Kaladhungi", "Ramnagar", "Kotabagh", "Bhimtal"),
    "Udham Singh Nagar": b("Rudrapur", "Kashipur", "Khatima", "Sitarganj", "Bazpur", "Jaspur"),
    "Pauri Garhwal": b("Pauri", "Srinagar", "Kotdwar", "Lansdowne", "Yamkeshwar"),
    "Tehri Garhwal": b("New Tehri", "Pratapnagar", "Devprayag", "Narendranagar", "Ghansali"),
    Almora: b("Almora", "Ranikhet", "Dwarahat", "Bhikiyasain", "Chaukhutia"),
    Pithoragarh: b("Pithoragarh", "Dharchula", "Munsiyari", "Berinag", "Gangolihat"),
    Chamoli: b("Gopeshwar", "Joshimath", "Karnaprayag", "Gairsain", "Tharali"),
    Rudraprayag: b("Rudraprayag", "Ukhimath", "Jakholi", "Agastyamuni"),
    Champawat: b("Champawat", "Lohaghat", "Tanakpur", "Pati"),
    Bageshwar: b("Bageshwar", "Kapkot", "Garur"),
    Uttarkashi: b("Uttarkashi", "Barkot", "Bhatwari", "Dunda", "Purola"),
  },
  "West Bengal": {
    Kolkata: b("Park Street", "Ballygunge", "Alipore", "Behala", "Jadavpur"),
    "North 24 Parganas": b("Barasat", "Barrackpore", "Bidhannagar", "Basirhat", "Bongaon"),
    "South 24 Parganas": b("Alipore", "Diamond Harbour", "Baruipur", "Canning", "Kakdwip"),
    Howrah: b("Howrah Sadar", "Uluberia", "Bagnan", "Amta", "Domjur"),
    Hooghly: b("Chinsurah", "Serampore", "Arambagh", "Chandannagar"),
    Darjeeling: b("Darjeeling", "Kurseong", "Mirik", "Siliguri"),
    Jalpaiguri: b("Jalpaiguri", "Mal", "Maynaguri", "Rajganj"),
    "Cooch Behar": b("Cooch Behar", "Dinhata", "Mathabhanga", "Mekhliganj"),
    Murshidabad: b("Berhampore", "Kandi", "Lalbagh", "Jangipur"),
    Nadia: b("Krishnanagar", "Ranaghat", "Kalyani", "Tehatta"),
    "Bardhaman (Purba)": b("Bardhaman", "Kalna", "Katwa"),
    "Bardhaman (Paschim)": b("Asansol", "Durgapur", "Raniganj"),
    Birbhum: b("Suri", "Bolpur", "Rampurhat"),
    Bankura: b("Bankura Sadar", "Khatra", "Bishnupur"),
  },
  "Andaman and Nicobar Islands": {
    "South Andaman": b("Port Blair", "Ferrargunj", "Little Andaman"),
    "North and Middle Andaman": b("Mayabunder", "Rangat", "Diglipur"),
    Nicobar: b("Car Nicobar", "Nancowry", "Great Nicobar"),
  },
  Chandigarh: {
    Chandigarh: b("Sector 17", "Sector 22", "Sector 35", "Mani Majra", "Burail"),
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": b("Silvassa", "Dadra", "Khanvel"),
    Daman: b("Daman", "Moti Daman", "Nani Daman"),
    Diu: b("Diu", "Ghoghla", "Vanakbara"),
  },
  Delhi: {
    "New Delhi": b("Connaught Place", "Chanakyapuri", "Parliament Street"),
    "Central Delhi": b("Karol Bagh", "Pahar Ganj", "Darya Ganj"),
    "North Delhi": b("Civil Lines", "Sadar Bazaar", "Kotwali"),
    "South Delhi": b("Hauz Khas", "Saket", "Defence Colony", "Kalkaji"),
    "East Delhi": b("Preet Vihar", "Vivek Vihar", "Gandhi Nagar"),
    "West Delhi": b("Rajouri Garden", "Punjabi Bagh", "Patel Nagar"),
    "North East Delhi": b("Seelampur", "Shahdara", "Yamuna Vihar"),
    "North West Delhi": b("Rohini", "Narela", "Saraswati Vihar"),
    "South West Delhi": b("Dwarka", "Najafgarh", "Vasant Vihar"),
    "South East Delhi": b("Sarita Vihar", "Kalindi Kunj", "Defence Colony"),
    Shahdara: b("Shahdara", "Seemapuri", "Vivek Vihar"),
  },
  "Jammu and Kashmir": {
    Srinagar: b("Srinagar North", "Srinagar South", "Chanapora", "Eidgah"),
    Jammu: b("Jammu North", "Jammu South", "Bahu", "R.S. Pura", "Akhnoor"),
    Anantnag: b("Anantnag", "Bijbehara", "Pahalgam", "Dooru"),
    Baramulla: b("Baramulla", "Sopore", "Uri", "Pattan"),
    Budgam: b("Budgam", "Chadoora", "Beerwah", "Chrar-i-Sharief"),
    Kupwara: b("Kupwara", "Handwara", "Karnah", "Kralpora"),
    Pulwama: b("Pulwama", "Pampore", "Tral", "Awantipora"),
    Kathua: b("Kathua", "Hiranagar", "Basohli", "Billawar"),
    Udhampur: b("Udhampur", "Chenani", "Ramnagar", "Majalta"),
    Rajouri: b("Rajouri", "Nowshera", "Sunderbani", "Kalakote"),
    Poonch: b("Poonch", "Mendhar", "Surankote"),
  },
  Ladakh: {
    Leh: b("Leh", "Nubra", "Khaltse", "Nyoma", "Durbuk"),
    Kargil: b("Kargil", "Sankoo", "Drass", "Zanskar", "Shakar Chiktan"),
  },
  Lakshadweep: {
    Lakshadweep: b("Kavaratti", "Agatti", "Amini", "Andrott", "Kalpeni", "Minicoy"),
  },
  Puducherry: {
    Puducherry: b("Puducherry", "Ozhukarai", "Villianur", "Bahour", "Ariyankuppam"),
    Karaikal: b("Karaikal", "Kottucherry", "Nedungadu", "Thirunallar"),
    Mahe: b("Mahe", "Palloor", "Pandakkal"),
    Yanam: b("Yanam"),
  },
};

export const INDIAN_STATES: string[] = Object.keys(INDIA_GEO).sort();

export function getDistricts(state: string): string[] {
  if (!state || !INDIA_GEO[state]) return [];
  return Object.keys(INDIA_GEO[state]).sort();
}

export function getBlocks(state: string, district: string): string[] {
  if (!state || !district || !INDIA_GEO[state]?.[district]) return [];
  return [...INDIA_GEO[state][district]].sort();
}
