import type { SectionType } from "@/lib/website-editor.functions";

export const TEMPLATE_CATEGORIES = [
  "All",
  "Hair Salon",
  "Beauty Parlour",
  "Spa",
  "Tattoo",
  "Nail Art",
  "Massage",
  "Barber",
] as const;

export type TemplateCategory = Exclude<(typeof TEMPLATE_CATEGORIES)[number], "All">;

export type TemplateCatalogItem = {
  key: string;
  name: string;
  category: TemplateCategory;
  description: string;
  tags: string[];
  thumbnailUrl: string;
  primary: string;
  secondary: string;
  background: string;
  text: string;
  headingFont: string;
  bodyFont: string;
  buttonStyle: "rounded" | "pill" | "square";
  heroStyle: "split" | "centered" | "editorial";
  visibleOrder: SectionType[];
};

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=75`;
const hair = [
  image("photo-1560066984-138dadb4c035"),
  image("photo-1521590832167-7bcbfaa6381f"),
  image("photo-1522337360788-8b13dee7a37e"),
];
const beauty = [
  image("photo-1487412947147-5cebf100ffc2"),
  image("photo-1512496015851-a90fb38ba796"),
  image("photo-1524504388940-b1c1722653e1"),
];
const spa = [
  image("photo-1540555700478-4be289fbecef"),
  image("photo-1600334089648-b0d9d3028eb2"),
  image("photo-1596178065887-1198b6148b2b"),
];
const tattoo = [
  image("photo-1565058379802-bbe93b2f703a"),
  image("photo-1542727365-19732a80dcfd"),
  image("photo-1598371839696-5c5bb00bdc28"),
];
const nails = [
  image("photo-1604654894610-df63bc536371"),
  image("photo-1610992015732-2449b76344bc"),
  image("photo-1519014816548-bf5fe059798b"),
];
const massage = [
  image("photo-1544161515-4ab6ce6db874"),
  image("photo-1600334129128-685c5582fd35"),
  image("photo-1519823551278-64ac92734fb1"),
];
const barber = [
  image("photo-1503951914875-452162b0f3f1"),
  image("photo-1621605815971-fbc98d665033"),
  image("photo-1585747860715-2ba37e788b70"),
];

const full: SectionType[] = [
  "hero",
  "about",
  "services",
  "staff",
  "gallery",
  "rate_card",
  "packages",
  "offers",
  "membership",
  "blog",
  "contact",
];
const portfolio: SectionType[] = [
  "hero",
  "gallery",
  "about",
  "services",
  "staff",
  "offers",
  "contact",
];
const serviceFirst: SectionType[] = [
  "hero",
  "services",
  "rate_card",
  "offers",
  "staff",
  "gallery",
  "contact",
];
const wellness: SectionType[] = [
  "hero",
  "about",
  "services",
  "packages",
  "membership",
  "gallery",
  "staff",
  "contact",
];

export const TEMPLATE_CATALOG: TemplateCatalogItem[] = [
  {
    key: "modern-hair-studio",
    name: "Modern Hair Studio",
    category: "Hair Salon",
    description: "Bright split-hero layout for modern cuts, colour and stylists.",
    tags: ["Split hero", "Stylists", "Rate card"],
    thumbnailUrl: hair[0],
    primary: "#4F46E5",
    secondary: "#F59E0B",
    background: "#F8FAFC",
    text: "#0F172A",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    buttonStyle: "pill",
    heroStyle: "split",
    visibleOrder: serviceFirst,
  },
  {
    key: "luxury-hair-lounge",
    name: "Luxury Hair Lounge",
    category: "Hair Salon",
    description: "Editorial black-and-gold experience for premium hair lounges.",
    tags: ["Luxury", "Editorial", "Membership"],
    thumbnailUrl: hair[1],
    primary: "#D4AF37",
    secondary: "#F5E6C8",
    background: "#0B0B0B",
    text: "#FFFFFF",
    headingFont: "Playfair Display",
    bodyFont: "Lora",
    buttonStyle: "rounded",
    heroStyle: "editorial",
    visibleOrder: full,
  },
  {
    key: "unisex-salon-pro",
    name: "Unisex Salon Pro",
    category: "Hair Salon",
    description: "Fast service-first booking layout for busy unisex salons.",
    tags: ["Unisex", "Fast booking", "Offers"],
    thumbnailUrl: hair[2],
    primary: "#0F766E",
    secondary: "#FB7185",
    background: "#F0FDFA",
    text: "#134E4A",
    headingFont: "Poppins",
    bodyFont: "Poppins",
    buttonStyle: "rounded",
    heroStyle: "centered",
    visibleOrder: serviceFirst,
  },
  {
    key: "bridal-beauty-studio",
    name: "Bridal Beauty Studio",
    category: "Beauty Parlour",
    description: "Bridal package-led design with portfolios and consultation CTA.",
    tags: ["Bridal", "Packages", "Portfolio"],
    thumbnailUrl: beauty[0],
    primary: "#BE185D",
    secondary: "#F9A8D4",
    background: "#FFF7FA",
    text: "#3F1630",
    headingFont: "Playfair Display",
    bodyFont: "Lora",
    buttonStyle: "pill",
    heroStyle: "editorial",
    visibleOrder: ["hero", "packages", "gallery", "about", "services", "staff", "contact"],
  },
  {
    key: "elegant-beauty-parlour",
    name: "Elegant Beauty Parlour",
    category: "Beauty Parlour",
    description: "Soft, trusted and service-rich layout for neighbourhood parlours.",
    tags: ["Elegant", "Services", "Reviews"],
    thumbnailUrl: beauty[1],
    primary: "#9D174D",
    secondary: "#FBCFE8",
    background: "#FFFBFE",
    text: "#4A1735",
    headingFont: "Lora",
    bodyFont: "Inter",
    buttonStyle: "rounded",
    heroStyle: "split",
    visibleOrder: full,
  },
  {
    key: "makeup-artist-portfolio",
    name: "Makeup Artist Portfolio",
    category: "Beauty Parlour",
    description: "Visual portfolio-first layout for makeup artists and studios.",
    tags: ["Gallery first", "Artists", "Social"],
    thumbnailUrl: beauty[2],
    primary: "#111827",
    secondary: "#E11D48",
    background: "#F5F3EE",
    text: "#1A1A1A",
    headingFont: "Playfair Display",
    bodyFont: "Montserrat",
    buttonStyle: "square",
    heroStyle: "editorial",
    visibleOrder: portfolio,
  },
  {
    key: "luxury-wellness-spa",
    name: "Luxury Wellness Spa",
    category: "Spa",
    description: "Immersive wellness journey with therapies, packages and membership.",
    tags: ["Therapies", "Membership", "Ambience"],
    thumbnailUrl: spa[0],
    primary: "#365314",
    secondary: "#D9F99D",
    background: "#F7FEE7",
    text: "#1A2E05",
    headingFont: "Playfair Display",
    bodyFont: "Lora",
    buttonStyle: "pill",
    heroStyle: "split",
    visibleOrder: wellness,
  },
  {
    key: "ayurveda-relaxation",
    name: "Ayurveda & Relaxation",
    category: "Spa",
    description: "Warm natural design for Ayurveda rituals and healing packages.",
    tags: ["Ayurveda", "Natural", "Packages"],
    thumbnailUrl: spa[1],
    primary: "#92400E",
    secondary: "#FDE68A",
    background: "#FFFBEB",
    text: "#451A03",
    headingFont: "Merriweather",
    bodyFont: "Lora",
    buttonStyle: "rounded",
    heroStyle: "centered",
    visibleOrder: wellness,
  },
  {
    key: "minimal-spa-retreat",
    name: "Minimal Spa Retreat",
    category: "Spa",
    description: "Calm whitespace-led layout focused on therapies and easy booking.",
    tags: ["Minimal", "Calm", "Mobile first"],
    thumbnailUrl: spa[2],
    primary: "#0F766E",
    secondary: "#99F6E4",
    background: "#F8FAFC",
    text: "#134E4A",
    headingFont: "Montserrat",
    bodyFont: "Inter",
    buttonStyle: "square",
    heroStyle: "centered",
    visibleOrder: ["hero", "services", "about", "gallery", "contact"],
  },
  {
    key: "dark-ink-studio",
    name: "Dark Ink Studio",
    category: "Tattoo",
    description: "Bold dark portfolio with tattoo styles, artists and aftercare.",
    tags: ["Dark", "Portfolio", "Aftercare"],
    thumbnailUrl: tattoo[0],
    primary: "#EF4444",
    secondary: "#A3A3A3",
    background: "#09090B",
    text: "#FAFAFA",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    buttonStyle: "square",
    heroStyle: "editorial",
    visibleOrder: portfolio,
  },
  {
    key: "urban-tattoo-artist",
    name: "Urban Tattoo Artist",
    category: "Tattoo",
    description: "Street-inspired artist profile with flash gallery and booking.",
    tags: ["Urban", "Artist", "Flash gallery"],
    thumbnailUrl: tattoo[1],
    primary: "#7C3AED",
    secondary: "#22D3EE",
    background: "#111827",
    text: "#F9FAFB",
    headingFont: "Montserrat",
    bodyFont: "Inter",
    buttonStyle: "pill",
    heroStyle: "split",
    visibleOrder: ["hero", "staff", "gallery", "services", "about", "contact"],
  },
  {
    key: "premium-tattoo-portfolio",
    name: "Premium Tattoo Portfolio",
    category: "Tattoo",
    description: "Refined monochrome showcase for premium custom tattoo work.",
    tags: ["Premium", "Monochrome", "Portfolio"],
    thumbnailUrl: tattoo[2],
    primary: "#F5F5F4",
    secondary: "#A8A29E",
    background: "#1C1917",
    text: "#FAFAF9",
    headingFont: "Playfair Display",
    bodyFont: "Montserrat",
    buttonStyle: "square",
    heroStyle: "editorial",
    visibleOrder: portfolio,
  },
  {
    key: "pastel-nail-studio",
    name: "Pastel Nail Studio",
    category: "Nail Art",
    description: "Playful pastel grid for nail designs, services and packages.",
    tags: ["Pastel", "Design gallery", "Packages"],
    thumbnailUrl: nails[0],
    primary: "#A855F7",
    secondary: "#F9A8D4",
    background: "#FDF4FF",
    text: "#581C87",
    headingFont: "Poppins",
    bodyFont: "Poppins",
    buttonStyle: "pill",
    heroStyle: "centered",
    visibleOrder: ["hero", "gallery", "services", "packages", "offers", "contact"],
  },
  {
    key: "luxury-nail-bar",
    name: "Luxury Nail Bar",
    category: "Nail Art",
    description: "Polished editorial layout for premium nail bars and memberships.",
    tags: ["Luxury", "Membership", "Rate card"],
    thumbnailUrl: nails[1],
    primary: "#C084FC",
    secondary: "#FDE68A",
    background: "#18181B",
    text: "#FAFAFA",
    headingFont: "Playfair Display",
    bodyFont: "Lora",
    buttonStyle: "rounded",
    heroStyle: "split",
    visibleOrder: full,
  },
  {
    key: "creative-nail-artist",
    name: "Creative Nail Artist",
    category: "Nail Art",
    description: "Portfolio-first creator page for custom nail artists.",
    tags: ["Creative", "Portfolio", "Social"],
    thumbnailUrl: nails[2],
    primary: "#DB2777",
    secondary: "#22D3EE",
    background: "#FFF1F2",
    text: "#4C0519",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    buttonStyle: "square",
    heroStyle: "editorial",
    visibleOrder: portfolio,
  },
  {
    key: "therapeutic-massage",
    name: "Therapeutic Massage",
    category: "Massage",
    description: "Clinical-trust layout for therapeutic massage and recovery.",
    tags: ["Therapy", "Trust", "Duration"],
    thumbnailUrl: massage[0],
    primary: "#0369A1",
    secondary: "#BAE6FD",
    background: "#F0F9FF",
    text: "#0C4A6E",
    headingFont: "Merriweather",
    bodyFont: "Inter",
    buttonStyle: "rounded",
    heroStyle: "split",
    visibleOrder: serviceFirst,
  },
  {
    key: "relaxation-massage-center",
    name: "Relaxation Massage Center",
    category: "Massage",
    description: "Warm calming design for relaxation and wellness packages.",
    tags: ["Relaxation", "Packages", "Wellness"],
    thumbnailUrl: massage[1],
    primary: "#A16207",
    secondary: "#FDE68A",
    background: "#FFFBEB",
    text: "#422006",
    headingFont: "Lora",
    bodyFont: "Inter",
    buttonStyle: "pill",
    heroStyle: "centered",
    visibleOrder: wellness,
  },
  {
    key: "premium-body-wellness",
    name: "Premium Body Wellness",
    category: "Massage",
    description: "Luxury membership-focused body wellness experience.",
    tags: ["Premium", "Membership", "Therapists"],
    thumbnailUrl: massage[2],
    primary: "#C4B5FD",
    secondary: "#FBCFE8",
    background: "#171024",
    text: "#FAF5FF",
    headingFont: "Playfair Display",
    bodyFont: "Montserrat",
    buttonStyle: "pill",
    heroStyle: "editorial",
    visibleOrder: full,
  },
  {
    key: "classic-barber-shop",
    name: "Classic Barber Shop",
    category: "Barber",
    description: "Traditional shopfront layout with price list and barber team.",
    tags: ["Classic", "Price list", "Team"],
    thumbnailUrl: barber[0],
    primary: "#B91C1C",
    secondary: "#F5F5F4",
    background: "#1C1917",
    text: "#FAFAF9",
    headingFont: "Merriweather",
    bodyFont: "Inter",
    buttonStyle: "square",
    heroStyle: "split",
    visibleOrder: serviceFirst,
  },
  {
    key: "modern-mens-grooming",
    name: "Modern Men’s Grooming",
    category: "Barber",
    description: "Clean modern booking layout for cuts, fades and grooming.",
    tags: ["Modern", "Fast booking", "Combos"],
    thumbnailUrl: barber[1],
    primary: "#2563EB",
    secondary: "#93C5FD",
    background: "#F8FAFC",
    text: "#0F172A",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    buttonStyle: "pill",
    heroStyle: "centered",
    visibleOrder: serviceFirst,
  },
  {
    key: "royal-beard-hair-studio",
    name: "Royal Beard & Hair Studio",
    category: "Barber",
    description: "Royal dark-and-gold brand experience for premium grooming.",
    tags: ["Royal", "Beard", "Membership"],
    thumbnailUrl: barber[2],
    primary: "#D4AF37",
    secondary: "#FDE68A",
    background: "#0C0A09",
    text: "#FAFAF9",
    headingFont: "Playfair Display",
    bodyFont: "Lora",
    buttonStyle: "rounded",
    heroStyle: "editorial",
    visibleOrder: full,
  },
];
