/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OwnerSignupRouteImport } from './routes/owner-signup'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForOwnersRouteImport } from './routes/for-owners'
import { Route as DistrictBusinessPartnerRouteImport } from './routes/district-business-partner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as SiteBusinessSlugRouteImport } from './routes/site.$businessSlug'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as PortalSponsoredRouteImport } from './routes/portal.sponsored'
import { Route as PortalPromotionsRouteImport } from './routes/portal.promotions'
import { Route as PortalProductsRouteImport } from './routes/portal.products'
import { Route as PortalPricingRouteImport } from './routes/portal.pricing'
import { Route as PortalLeadsRouteImport } from './routes/portal.leads'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalContactRouteImport } from './routes/portal.contact'
import { Route as PortalBusinessPagesRouteImport } from './routes/portal.business-pages'
import { Route as PartnerGrowthRouteImport } from './routes/partner.growth'
import { Route as PartnerDistrictRouteImport } from './routes/partner.district'
import { Route as PartnerDistributorRouteImport } from './routes/partner.distributor'
import { Route as OwnerWebsiteRouteImport } from './routes/owner.website'
import { Route as OwnerTemplatesRouteImport } from './routes/owner.templates'
import { Route as OwnerStaffRouteImport } from './routes/owner.staff'
import { Route as OwnerSetupWizardRouteImport } from './routes/owner.setup-wizard'
import { Route as OwnerServicesRouteImport } from './routes/owner.services'
import { Route as OwnerReviewsRouteImport } from './routes/owner.reviews'
import { Route as OwnerRegisterBusinessRouteImport } from './routes/owner.register-business'
import { Route as OwnerPendingRouteImport } from './routes/owner.pending'
import { Route as OwnerPaymentsRouteImport } from './routes/owner.payments'
import { Route as OwnerOnboardingRouteImport } from './routes/owner.onboarding'
import { Route as OwnerMarketingRouteImport } from './routes/owner.marketing'
import { Route as OwnerJobsRouteImport } from './routes/owner.jobs'
import { Route as OwnerGalleryRouteImport } from './routes/owner.gallery'
import { Route as OwnerCrmRouteImport } from './routes/owner.crm'
import { Route as OwnerCreateWebsiteRouteImport } from './routes/owner.create-website'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as JobsSearchRouteImport } from './routes/jobs.search'
import { Route as JobsProfileRouteImport } from './routes/jobs.profile'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as DistrictBusinessPartnerSlugRouteImport } from './routes/district-business-partner.$slug'
import { Route as DistributorSlugRouteImport } from './routes/distributor.$slug'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRewardsRouteImport } from './routes/dashboard.rewards'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardQrHistoryRouteImport } from './routes/dashboard.qr-history'
import { Route as DashboardOffersRouteImport } from './routes/dashboard.offers'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMembershipRouteImport } from './routes/dashboard.membership'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRankingsRouteImport } from './routes/admin.rankings'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdvertisingRouteImport } from './routes/admin.advertising'
import { Route as PortalDistributorsIndexRouteImport } from './routes/portal.distributors.index'
import { Route as PortalBrandsIndexRouteImport } from './routes/portal.brands.index'
import { Route as PortalDistributorsRegisterRouteImport } from './routes/portal.distributors.register'
import { Route as PortalDistributorsSlugRouteImport } from './routes/portal.distributors.$slug'
import { Route as PortalBrandsRegisterRouteImport } from './routes/portal.brands.register'
import { Route as PortalBrandsSlugRouteImport } from './routes/portal.brands.$slug'
import { Route as OwnerJobsNewRouteImport } from './routes/owner.jobs.new'
import { Route as DashboardBookingsIdRouteImport } from './routes/dashboard.bookings.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksReleaseExpiredBookingsRouteImport } from './routes/api/public/hooks/release-expired-bookings'
import { Route as ApiPublicHooksRecomputeRankingsRouteImport } from './routes/api/public/hooks/recompute-rankings'
import { Route as ApiPublicHooksRecomputeInsightsRouteImport } from './routes/api/public/hooks/recompute-insights'
import { Route as ApiPublicHooksProcessSettlementsRouteImport } from './routes/api/public/hooks/process-settlements'
import { Route as ApiPublicAuthForgotPasswordRouteImport } from './routes/api/public/auth/forgot-password'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSignupRoute = OwnerSignupRouteImport.update({
  id: '/owner-signup',
  path: '/owner-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOwnersRoute = ForOwnersRouteImport.update({
  id: '/for-owners',
  path: '/for-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictBusinessPartnerRoute = DistrictBusinessPartnerRouteImport.update({
  id: '/district-business-partner',
  path: '/district-business-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteBusinessSlugRoute = SiteBusinessSlugRouteImport.update({
  id: '/site/$businessSlug',
  path: '/site/$businessSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSponsoredRoute = PortalSponsoredRouteImport.update({
  id: '/portal/sponsored',
  path: '/portal/sponsored',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPromotionsRoute = PortalPromotionsRouteImport.update({
  id: '/portal/promotions',
  path: '/portal/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProductsRoute = PortalProductsRouteImport.update({
  id: '/portal/products',
  path: '/portal/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPricingRoute = PortalPricingRouteImport.update({
  id: '/portal/pricing',
  path: '/portal/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLeadsRoute = PortalLeadsRouteImport.update({
  id: '/portal/leads',
  path: '/portal/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalContactRoute = PortalContactRouteImport.update({
  id: '/portal/contact',
  path: '/portal/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBusinessPagesRoute = PortalBusinessPagesRouteImport.update({
  id: '/portal/business-pages',
  path: '/portal/business-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerGrowthRoute = PartnerGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDistrictRoute = PartnerDistrictRouteImport.update({
  id: '/district',
  path: '/district',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDistributorRoute = PartnerDistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => PartnerRoute,
} as any)
const OwnerWebsiteRoute = OwnerWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTemplatesRoute = OwnerTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStaffRoute = OwnerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSetupWizardRoute = OwnerSetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerServicesRoute = OwnerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReviewsRoute = OwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRegisterBusinessRoute = OwnerRegisterBusinessRouteImport.update({
  id: '/register-business',
  path: '/register-business',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPendingRoute = OwnerPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPaymentsRoute = OwnerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOnboardingRoute = OwnerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMarketingRoute = OwnerMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerJobsRoute = OwnerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerGalleryRoute = OwnerGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCrmRoute = OwnerCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCreateWebsiteRoute = OwnerCreateWebsiteRouteImport.update({
  id: '/create-website',
  path: '/create-website',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerRoute,
} as any)
const JobsSearchRoute = JobsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => JobsRoute,
} as any)
const JobsProfileRoute = JobsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => JobsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const DistrictBusinessPartnerSlugRoute =
  DistrictBusinessPartnerSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => DistrictBusinessPartnerRoute,
  } as any)
const DistributorSlugRoute = DistributorSlugRouteImport.update({
  id: '/distributor/$slug',
  path: '/distributor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRewardsRoute = DashboardRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrHistoryRoute = DashboardQrHistoryRouteImport.update({
  id: '/qr-history',
  path: '/qr-history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffersRoute = DashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRankingsRoute = AdminRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisingRoute = AdminAdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => AdminRoute,
} as any)
const PortalDistributorsIndexRoute = PortalDistributorsIndexRouteImport.update({
  id: '/portal/distributors/',
  path: '/portal/distributors/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBrandsIndexRoute = PortalBrandsIndexRouteImport.update({
  id: '/portal/brands/',
  path: '/portal/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDistributorsRegisterRoute =
  PortalDistributorsRegisterRouteImport.update({
    id: '/portal/distributors/register',
    path: '/portal/distributors/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalDistributorsSlugRoute = PortalDistributorsSlugRouteImport.update({
  id: '/portal/distributors/$slug',
  path: '/portal/distributors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBrandsRegisterRoute = PortalBrandsRegisterRouteImport.update({
  id: '/portal/brands/register',
  path: '/portal/brands/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBrandsSlugRoute = PortalBrandsSlugRouteImport.update({
  id: '/portal/brands/$slug',
  path: '/portal/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerJobsNewRoute = OwnerJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerJobsRoute,
} as any)
const DashboardBookingsIdRoute = DashboardBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksReleaseExpiredBookingsRoute =
  ApiPublicHooksReleaseExpiredBookingsRouteImport.update({
    id: '/api/public/hooks/release-expired-bookings',
    path: '/api/public/hooks/release-expired-bookings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecomputeRankingsRoute =
  ApiPublicHooksRecomputeRankingsRouteImport.update({
    id: '/api/public/hooks/recompute-rankings',
    path: '/api/public/hooks/recompute-rankings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecomputeInsightsRoute =
  ApiPublicHooksRecomputeInsightsRouteImport.update({
    id: '/api/public/hooks/recompute-insights',
    path: '/api/public/hooks/recompute-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessSettlementsRoute =
  ApiPublicHooksProcessSettlementsRouteImport.update({
    id: '/api/public/hooks/process-settlements',
    path: '/api/public/hooks/process-settlements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthForgotPasswordRoute =
  ApiPublicAuthForgotPasswordRouteImport.update({
    id: '/api/public/auth/forgot-password',
    path: '/api/public/auth/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/district-business-partner': typeof DistrictBusinessPartnerRouteWithChildren
  '/for-owners': typeof ForOwnersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/offline': typeof OfflineRoute
  '/owner': typeof OwnerRouteWithChildren
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/owner-signup': typeof OwnerSignupRoute
  '/partner': typeof PartnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$slug': typeof BookSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/qr-history': typeof DashboardQrHistoryRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/distributor/$slug': typeof DistributorSlugRoute
  '/district-business-partner/$slug': typeof DistrictBusinessPartnerSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/profile': typeof JobsProfileRoute
  '/jobs/search': typeof JobsSearchRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/create-website': typeof OwnerCreateWebsiteRoute
  '/owner/crm': typeof OwnerCrmRoute
  '/owner/gallery': typeof OwnerGalleryRoute
  '/owner/jobs': typeof OwnerJobsRouteWithChildren
  '/owner/marketing': typeof OwnerMarketingRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/pending': typeof OwnerPendingRoute
  '/owner/register-business': typeof OwnerRegisterBusinessRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/setup-wizard': typeof OwnerSetupWizardRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/templates': typeof OwnerTemplatesRoute
  '/owner/website': typeof OwnerWebsiteRoute
  '/partner/distributor': typeof PartnerDistributorRoute
  '/partner/district': typeof PartnerDistrictRoute
  '/partner/growth': typeof PartnerGrowthRoute
  '/portal/business-pages': typeof PortalBusinessPagesRoute
  '/portal/contact': typeof PortalContactRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/pricing': typeof PortalPricingRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/promotions': typeof PortalPromotionsRoute
  '/portal/sponsored': typeof PortalSponsoredRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/site/$businessSlug': typeof SiteBusinessSlugRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/owner/jobs/new': typeof OwnerJobsNewRoute
  '/portal/brands/$slug': typeof PortalBrandsSlugRoute
  '/portal/brands/register': typeof PortalBrandsRegisterRoute
  '/portal/distributors/$slug': typeof PortalDistributorsSlugRoute
  '/portal/distributors/register': typeof PortalDistributorsRegisterRoute
  '/portal/brands/': typeof PortalBrandsIndexRoute
  '/portal/distributors/': typeof PortalDistributorsIndexRoute
  '/api/public/auth/forgot-password': typeof ApiPublicAuthForgotPasswordRoute
  '/api/public/hooks/process-settlements': typeof ApiPublicHooksProcessSettlementsRoute
  '/api/public/hooks/recompute-insights': typeof ApiPublicHooksRecomputeInsightsRoute
  '/api/public/hooks/recompute-rankings': typeof ApiPublicHooksRecomputeRankingsRoute
  '/api/public/hooks/release-expired-bookings': typeof ApiPublicHooksReleaseExpiredBookingsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/district-business-partner': typeof DistrictBusinessPartnerRouteWithChildren
  '/for-owners': typeof ForOwnersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/offline': typeof OfflineRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/owner-signup': typeof OwnerSignupRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$slug': typeof BookSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/qr-history': typeof DashboardQrHistoryRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/distributor/$slug': typeof DistributorSlugRoute
  '/district-business-partner/$slug': typeof DistrictBusinessPartnerSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/profile': typeof JobsProfileRoute
  '/jobs/search': typeof JobsSearchRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/create-website': typeof OwnerCreateWebsiteRoute
  '/owner/crm': typeof OwnerCrmRoute
  '/owner/gallery': typeof OwnerGalleryRoute
  '/owner/jobs': typeof OwnerJobsRouteWithChildren
  '/owner/marketing': typeof OwnerMarketingRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/pending': typeof OwnerPendingRoute
  '/owner/register-business': typeof OwnerRegisterBusinessRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/setup-wizard': typeof OwnerSetupWizardRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/templates': typeof OwnerTemplatesRoute
  '/owner/website': typeof OwnerWebsiteRoute
  '/partner/distributor': typeof PartnerDistributorRoute
  '/partner/district': typeof PartnerDistrictRoute
  '/partner/growth': typeof PartnerGrowthRoute
  '/portal/business-pages': typeof PortalBusinessPagesRoute
  '/portal/contact': typeof PortalContactRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/pricing': typeof PortalPricingRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/promotions': typeof PortalPromotionsRoute
  '/portal/sponsored': typeof PortalSponsoredRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/site/$businessSlug': typeof SiteBusinessSlugRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/dashboard': typeof DashboardIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/portal': typeof PortalIndexRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/owner/jobs/new': typeof OwnerJobsNewRoute
  '/portal/brands/$slug': typeof PortalBrandsSlugRoute
  '/portal/brands/register': typeof PortalBrandsRegisterRoute
  '/portal/distributors/$slug': typeof PortalDistributorsSlugRoute
  '/portal/distributors/register': typeof PortalDistributorsRegisterRoute
  '/portal/brands': typeof PortalBrandsIndexRoute
  '/portal/distributors': typeof PortalDistributorsIndexRoute
  '/api/public/auth/forgot-password': typeof ApiPublicAuthForgotPasswordRoute
  '/api/public/hooks/process-settlements': typeof ApiPublicHooksProcessSettlementsRoute
  '/api/public/hooks/recompute-insights': typeof ApiPublicHooksRecomputeInsightsRoute
  '/api/public/hooks/recompute-rankings': typeof ApiPublicHooksRecomputeRankingsRoute
  '/api/public/hooks/release-expired-bookings': typeof ApiPublicHooksReleaseExpiredBookingsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/district-business-partner': typeof DistrictBusinessPartnerRouteWithChildren
  '/for-owners': typeof ForOwnersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/offline': typeof OfflineRoute
  '/owner': typeof OwnerRouteWithChildren
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/owner-signup': typeof OwnerSignupRoute
  '/partner': typeof PartnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$slug': typeof BookSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/qr-history': typeof DashboardQrHistoryRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/distributor/$slug': typeof DistributorSlugRoute
  '/district-business-partner/$slug': typeof DistrictBusinessPartnerSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/profile': typeof JobsProfileRoute
  '/jobs/search': typeof JobsSearchRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/create-website': typeof OwnerCreateWebsiteRoute
  '/owner/crm': typeof OwnerCrmRoute
  '/owner/gallery': typeof OwnerGalleryRoute
  '/owner/jobs': typeof OwnerJobsRouteWithChildren
  '/owner/marketing': typeof OwnerMarketingRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/pending': typeof OwnerPendingRoute
  '/owner/register-business': typeof OwnerRegisterBusinessRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/setup-wizard': typeof OwnerSetupWizardRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/templates': typeof OwnerTemplatesRoute
  '/owner/website': typeof OwnerWebsiteRoute
  '/partner/distributor': typeof PartnerDistributorRoute
  '/partner/district': typeof PartnerDistrictRoute
  '/partner/growth': typeof PartnerGrowthRoute
  '/portal/business-pages': typeof PortalBusinessPagesRoute
  '/portal/contact': typeof PortalContactRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/pricing': typeof PortalPricingRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/promotions': typeof PortalPromotionsRoute
  '/portal/sponsored': typeof PortalSponsoredRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/site/$businessSlug': typeof SiteBusinessSlugRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/owner/jobs/new': typeof OwnerJobsNewRoute
  '/portal/brands/$slug': typeof PortalBrandsSlugRoute
  '/portal/brands/register': typeof PortalBrandsRegisterRoute
  '/portal/distributors/$slug': typeof PortalDistributorsSlugRoute
  '/portal/distributors/register': typeof PortalDistributorsRegisterRoute
  '/portal/brands/': typeof PortalBrandsIndexRoute
  '/portal/distributors/': typeof PortalDistributorsIndexRoute
  '/api/public/auth/forgot-password': typeof ApiPublicAuthForgotPasswordRoute
  '/api/public/hooks/process-settlements': typeof ApiPublicHooksProcessSettlementsRoute
  '/api/public/hooks/recompute-insights': typeof ApiPublicHooksRecomputeInsightsRoute
  '/api/public/hooks/recompute-rankings': typeof ApiPublicHooksRecomputeRankingsRoute
  '/api/public/hooks/release-expired-bookings': typeof ApiPublicHooksReleaseExpiredBookingsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/district-business-partner'
    | '/for-owners'
    | '/forgot-password'
    | '/help'
    | '/jobs'
    | '/login'
    | '/membership'
    | '/offline'
    | '/owner'
    | '/owner-dashboard'
    | '/owner-signup'
    | '/partner'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/businesses'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/rankings'
    | '/admin/reviews'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/book/$slug'
    | '/brand/$slug'
    | '/category/$slug'
    | '/dashboard/activity'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/membership'
    | '/dashboard/notifications'
    | '/dashboard/offers'
    | '/dashboard/qr-history'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/wallet'
    | '/distributor/$slug'
    | '/district-business-partner/$slug'
    | '/jobs/$jobId'
    | '/jobs/profile'
    | '/jobs/search'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/create-website'
    | '/owner/crm'
    | '/owner/gallery'
    | '/owner/jobs'
    | '/owner/marketing'
    | '/owner/onboarding'
    | '/owner/payments'
    | '/owner/pending'
    | '/owner/register-business'
    | '/owner/reviews'
    | '/owner/services'
    | '/owner/setup-wizard'
    | '/owner/staff'
    | '/owner/templates'
    | '/owner/website'
    | '/partner/distributor'
    | '/partner/district'
    | '/partner/growth'
    | '/portal/business-pages'
    | '/portal/contact'
    | '/portal/dashboard'
    | '/portal/leads'
    | '/portal/pricing'
    | '/portal/products'
    | '/portal/promotions'
    | '/portal/sponsored'
    | '/s/$slug'
    | '/shop/$slug'
    | '/site/$businessSlug'
    | '/staff/dashboard'
    | '/dashboard/'
    | '/owner/'
    | '/partner/'
    | '/portal/'
    | '/dashboard/bookings/$id'
    | '/owner/jobs/new'
    | '/portal/brands/$slug'
    | '/portal/brands/register'
    | '/portal/distributors/$slug'
    | '/portal/distributors/register'
    | '/portal/brands/'
    | '/portal/distributors/'
    | '/api/public/auth/forgot-password'
    | '/api/public/hooks/process-settlements'
    | '/api/public/hooks/recompute-insights'
    | '/api/public/hooks/recompute-rankings'
    | '/api/public/hooks/release-expired-bookings'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/contact'
    | '/district-business-partner'
    | '/for-owners'
    | '/forgot-password'
    | '/help'
    | '/jobs'
    | '/login'
    | '/membership'
    | '/offline'
    | '/owner-dashboard'
    | '/owner-signup'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/businesses'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/rankings'
    | '/admin/reviews'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/book/$slug'
    | '/brand/$slug'
    | '/category/$slug'
    | '/dashboard/activity'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/membership'
    | '/dashboard/notifications'
    | '/dashboard/offers'
    | '/dashboard/qr-history'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/wallet'
    | '/distributor/$slug'
    | '/district-business-partner/$slug'
    | '/jobs/$jobId'
    | '/jobs/profile'
    | '/jobs/search'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/create-website'
    | '/owner/crm'
    | '/owner/gallery'
    | '/owner/jobs'
    | '/owner/marketing'
    | '/owner/onboarding'
    | '/owner/payments'
    | '/owner/pending'
    | '/owner/register-business'
    | '/owner/reviews'
    | '/owner/services'
    | '/owner/setup-wizard'
    | '/owner/staff'
    | '/owner/templates'
    | '/owner/website'
    | '/partner/distributor'
    | '/partner/district'
    | '/partner/growth'
    | '/portal/business-pages'
    | '/portal/contact'
    | '/portal/dashboard'
    | '/portal/leads'
    | '/portal/pricing'
    | '/portal/products'
    | '/portal/promotions'
    | '/portal/sponsored'
    | '/s/$slug'
    | '/shop/$slug'
    | '/site/$businessSlug'
    | '/staff/dashboard'
    | '/dashboard'
    | '/owner'
    | '/partner'
    | '/portal'
    | '/dashboard/bookings/$id'
    | '/owner/jobs/new'
    | '/portal/brands/$slug'
    | '/portal/brands/register'
    | '/portal/distributors/$slug'
    | '/portal/distributors/register'
    | '/portal/brands'
    | '/portal/distributors'
    | '/api/public/auth/forgot-password'
    | '/api/public/hooks/process-settlements'
    | '/api/public/hooks/recompute-insights'
    | '/api/public/hooks/recompute-rankings'
    | '/api/public/hooks/release-expired-bookings'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/district-business-partner'
    | '/for-owners'
    | '/forgot-password'
    | '/help'
    | '/jobs'
    | '/login'
    | '/membership'
    | '/offline'
    | '/owner'
    | '/owner-dashboard'
    | '/owner-signup'
    | '/partner'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/businesses'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/rankings'
    | '/admin/reviews'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/book/$slug'
    | '/brand/$slug'
    | '/category/$slug'
    | '/dashboard/activity'
    | '/dashboard/bookings'
    | '/dashboard/favorites'
    | '/dashboard/membership'
    | '/dashboard/notifications'
    | '/dashboard/offers'
    | '/dashboard/qr-history'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/wallet'
    | '/distributor/$slug'
    | '/district-business-partner/$slug'
    | '/jobs/$jobId'
    | '/jobs/profile'
    | '/jobs/search'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/create-website'
    | '/owner/crm'
    | '/owner/gallery'
    | '/owner/jobs'
    | '/owner/marketing'
    | '/owner/onboarding'
    | '/owner/payments'
    | '/owner/pending'
    | '/owner/register-business'
    | '/owner/reviews'
    | '/owner/services'
    | '/owner/setup-wizard'
    | '/owner/staff'
    | '/owner/templates'
    | '/owner/website'
    | '/partner/distributor'
    | '/partner/district'
    | '/partner/growth'
    | '/portal/business-pages'
    | '/portal/contact'
    | '/portal/dashboard'
    | '/portal/leads'
    | '/portal/pricing'
    | '/portal/products'
    | '/portal/promotions'
    | '/portal/sponsored'
    | '/s/$slug'
    | '/shop/$slug'
    | '/site/$businessSlug'
    | '/staff/dashboard'
    | '/dashboard/'
    | '/owner/'
    | '/partner/'
    | '/portal/'
    | '/dashboard/bookings/$id'
    | '/owner/jobs/new'
    | '/portal/brands/$slug'
    | '/portal/brands/register'
    | '/portal/distributors/$slug'
    | '/portal/distributors/register'
    | '/portal/brands/'
    | '/portal/distributors/'
    | '/api/public/auth/forgot-password'
    | '/api/public/hooks/process-settlements'
    | '/api/public/hooks/recompute-insights'
    | '/api/public/hooks/recompute-rankings'
    | '/api/public/hooks/release-expired-bookings'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DistrictBusinessPartnerRoute: typeof DistrictBusinessPartnerRouteWithChildren
  ForOwnersRoute: typeof ForOwnersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  OfflineRoute: typeof OfflineRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerSignupRoute: typeof OwnerSignupRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookSlugRoute: typeof BookSlugRoute
  BrandSlugRoute: typeof BrandSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DistributorSlugRoute: typeof DistributorSlugRoute
  PortalBusinessPagesRoute: typeof PortalBusinessPagesRoute
  PortalContactRoute: typeof PortalContactRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLeadsRoute: typeof PortalLeadsRoute
  PortalPricingRoute: typeof PortalPricingRoute
  PortalProductsRoute: typeof PortalProductsRoute
  PortalPromotionsRoute: typeof PortalPromotionsRoute
  PortalSponsoredRoute: typeof PortalSponsoredRoute
  SSlugRoute: typeof SSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  SiteBusinessSlugRoute: typeof SiteBusinessSlugRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalBrandsSlugRoute: typeof PortalBrandsSlugRoute
  PortalBrandsRegisterRoute: typeof PortalBrandsRegisterRoute
  PortalDistributorsSlugRoute: typeof PortalDistributorsSlugRoute
  PortalDistributorsRegisterRoute: typeof PortalDistributorsRegisterRoute
  PortalBrandsIndexRoute: typeof PortalBrandsIndexRoute
  PortalDistributorsIndexRoute: typeof PortalDistributorsIndexRoute
  ApiPublicAuthForgotPasswordRoute: typeof ApiPublicAuthForgotPasswordRoute
  ApiPublicHooksProcessSettlementsRoute: typeof ApiPublicHooksProcessSettlementsRoute
  ApiPublicHooksRecomputeInsightsRoute: typeof ApiPublicHooksRecomputeInsightsRoute
  ApiPublicHooksRecomputeRankingsRoute: typeof ApiPublicHooksRecomputeRankingsRoute
  ApiPublicHooksReleaseExpiredBookingsRoute: typeof ApiPublicHooksReleaseExpiredBookingsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-signup': {
      id: '/owner-signup'
      path: '/owner-signup'
      fullPath: '/owner-signup'
      preLoaderRoute: typeof OwnerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-owners': {
      id: '/for-owners'
      path: '/for-owners'
      fullPath: '/for-owners'
      preLoaderRoute: typeof ForOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district-business-partner': {
      id: '/district-business-partner'
      path: '/district-business-partner'
      fullPath: '/district-business-partner'
      preLoaderRoute: typeof DistrictBusinessPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$businessSlug': {
      id: '/site/$businessSlug'
      path: '/site/$businessSlug'
      fullPath: '/site/$businessSlug'
      preLoaderRoute: typeof SiteBusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/sponsored': {
      id: '/portal/sponsored'
      path: '/portal/sponsored'
      fullPath: '/portal/sponsored'
      preLoaderRoute: typeof PortalSponsoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/promotions': {
      id: '/portal/promotions'
      path: '/portal/promotions'
      fullPath: '/portal/promotions'
      preLoaderRoute: typeof PortalPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/products': {
      id: '/portal/products'
      path: '/portal/products'
      fullPath: '/portal/products'
      preLoaderRoute: typeof PortalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/pricing': {
      id: '/portal/pricing'
      path: '/portal/pricing'
      fullPath: '/portal/pricing'
      preLoaderRoute: typeof PortalPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/leads': {
      id: '/portal/leads'
      path: '/portal/leads'
      fullPath: '/portal/leads'
      preLoaderRoute: typeof PortalLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/contact': {
      id: '/portal/contact'
      path: '/portal/contact'
      fullPath: '/portal/contact'
      preLoaderRoute: typeof PortalContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/business-pages': {
      id: '/portal/business-pages'
      path: '/portal/business-pages'
      fullPath: '/portal/business-pages'
      preLoaderRoute: typeof PortalBusinessPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/growth': {
      id: '/partner/growth'
      path: '/growth'
      fullPath: '/partner/growth'
      preLoaderRoute: typeof PartnerGrowthRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/district': {
      id: '/partner/district'
      path: '/district'
      fullPath: '/partner/district'
      preLoaderRoute: typeof PartnerDistrictRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/distributor': {
      id: '/partner/distributor'
      path: '/distributor'
      fullPath: '/partner/distributor'
      preLoaderRoute: typeof PartnerDistributorRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/owner/website': {
      id: '/owner/website'
      path: '/website'
      fullPath: '/owner/website'
      preLoaderRoute: typeof OwnerWebsiteRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/templates': {
      id: '/owner/templates'
      path: '/templates'
      fullPath: '/owner/templates'
      preLoaderRoute: typeof OwnerTemplatesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/staff': {
      id: '/owner/staff'
      path: '/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof OwnerStaffRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/setup-wizard': {
      id: '/owner/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/owner/setup-wizard'
      preLoaderRoute: typeof OwnerSetupWizardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/services': {
      id: '/owner/services'
      path: '/services'
      fullPath: '/owner/services'
      preLoaderRoute: typeof OwnerServicesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reviews': {
      id: '/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof OwnerReviewsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/register-business': {
      id: '/owner/register-business'
      path: '/register-business'
      fullPath: '/owner/register-business'
      preLoaderRoute: typeof OwnerRegisterBusinessRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/pending': {
      id: '/owner/pending'
      path: '/pending'
      fullPath: '/owner/pending'
      preLoaderRoute: typeof OwnerPendingRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/payments': {
      id: '/owner/payments'
      path: '/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof OwnerPaymentsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/onboarding': {
      id: '/owner/onboarding'
      path: '/onboarding'
      fullPath: '/owner/onboarding'
      preLoaderRoute: typeof OwnerOnboardingRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/marketing': {
      id: '/owner/marketing'
      path: '/marketing'
      fullPath: '/owner/marketing'
      preLoaderRoute: typeof OwnerMarketingRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/jobs': {
      id: '/owner/jobs'
      path: '/jobs'
      fullPath: '/owner/jobs'
      preLoaderRoute: typeof OwnerJobsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/gallery': {
      id: '/owner/gallery'
      path: '/gallery'
      fullPath: '/owner/gallery'
      preLoaderRoute: typeof OwnerGalleryRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/crm': {
      id: '/owner/crm'
      path: '/crm'
      fullPath: '/owner/crm'
      preLoaderRoute: typeof OwnerCrmRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/create-website': {
      id: '/owner/create-website'
      path: '/create-website'
      fullPath: '/owner/create-website'
      preLoaderRoute: typeof OwnerCreateWebsiteRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/jobs/search': {
      id: '/jobs/search'
      path: '/search'
      fullPath: '/jobs/search'
      preLoaderRoute: typeof JobsSearchRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/profile': {
      id: '/jobs/profile'
      path: '/profile'
      fullPath: '/jobs/profile'
      preLoaderRoute: typeof JobsProfileRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/district-business-partner/$slug': {
      id: '/district-business-partner/$slug'
      path: '/$slug'
      fullPath: '/district-business-partner/$slug'
      preLoaderRoute: typeof DistrictBusinessPartnerSlugRouteImport
      parentRoute: typeof DistrictBusinessPartnerRoute
    }
    '/distributor/$slug': {
      id: '/distributor/$slug'
      path: '/distributor/$slug'
      fullPath: '/distributor/$slug'
      preLoaderRoute: typeof DistributorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rewards': {
      id: '/dashboard/rewards'
      path: '/rewards'
      fullPath: '/dashboard/rewards'
      preLoaderRoute: typeof DashboardRewardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qr-history': {
      id: '/dashboard/qr-history'
      path: '/qr-history'
      fullPath: '/dashboard/qr-history'
      preLoaderRoute: typeof DashboardQrHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offers': {
      id: '/dashboard/offers'
      path: '/offers'
      fullPath: '/dashboard/offers'
      preLoaderRoute: typeof DashboardOffersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/membership': {
      id: '/dashboard/membership'
      path: '/membership'
      fullPath: '/dashboard/membership'
      preLoaderRoute: typeof DashboardMembershipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rankings': {
      id: '/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AdminRankingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertising': {
      id: '/admin/advertising'
      path: '/advertising'
      fullPath: '/admin/advertising'
      preLoaderRoute: typeof AdminAdvertisingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/distributors/': {
      id: '/portal/distributors/'
      path: '/portal/distributors'
      fullPath: '/portal/distributors/'
      preLoaderRoute: typeof PortalDistributorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/brands/': {
      id: '/portal/brands/'
      path: '/portal/brands'
      fullPath: '/portal/brands/'
      preLoaderRoute: typeof PortalBrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/distributors/register': {
      id: '/portal/distributors/register'
      path: '/portal/distributors/register'
      fullPath: '/portal/distributors/register'
      preLoaderRoute: typeof PortalDistributorsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/distributors/$slug': {
      id: '/portal/distributors/$slug'
      path: '/portal/distributors/$slug'
      fullPath: '/portal/distributors/$slug'
      preLoaderRoute: typeof PortalDistributorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/brands/register': {
      id: '/portal/brands/register'
      path: '/portal/brands/register'
      fullPath: '/portal/brands/register'
      preLoaderRoute: typeof PortalBrandsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/brands/$slug': {
      id: '/portal/brands/$slug'
      path: '/portal/brands/$slug'
      fullPath: '/portal/brands/$slug'
      preLoaderRoute: typeof PortalBrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/jobs/new': {
      id: '/owner/jobs/new'
      path: '/new'
      fullPath: '/owner/jobs/new'
      preLoaderRoute: typeof OwnerJobsNewRouteImport
      parentRoute: typeof OwnerJobsRoute
    }
    '/dashboard/bookings/$id': {
      id: '/dashboard/bookings/$id'
      path: '/$id'
      fullPath: '/dashboard/bookings/$id'
      preLoaderRoute: typeof DashboardBookingsIdRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/release-expired-bookings': {
      id: '/api/public/hooks/release-expired-bookings'
      path: '/api/public/hooks/release-expired-bookings'
      fullPath: '/api/public/hooks/release-expired-bookings'
      preLoaderRoute: typeof ApiPublicHooksReleaseExpiredBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recompute-rankings': {
      id: '/api/public/hooks/recompute-rankings'
      path: '/api/public/hooks/recompute-rankings'
      fullPath: '/api/public/hooks/recompute-rankings'
      preLoaderRoute: typeof ApiPublicHooksRecomputeRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recompute-insights': {
      id: '/api/public/hooks/recompute-insights'
      path: '/api/public/hooks/recompute-insights'
      fullPath: '/api/public/hooks/recompute-insights'
      preLoaderRoute: typeof ApiPublicHooksRecomputeInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-settlements': {
      id: '/api/public/hooks/process-settlements'
      path: '/api/public/hooks/process-settlements'
      fullPath: '/api/public/hooks/process-settlements'
      preLoaderRoute: typeof ApiPublicHooksProcessSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/forgot-password': {
      id: '/api/public/auth/forgot-password'
      path: '/api/public/auth/forgot-password'
      fullPath: '/api/public/auth/forgot-password'
      preLoaderRoute: typeof ApiPublicAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdvertisingRoute: typeof AdminAdvertisingRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRankingsRoute: typeof AdminRankingsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdvertisingRoute: AdminAdvertisingRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRankingsRoute: AdminRankingsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardBookingsRouteChildren {
  DashboardBookingsIdRoute: typeof DashboardBookingsIdRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsIdRoute: DashboardBookingsIdRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardMembershipRoute: typeof DashboardMembershipRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOffersRoute: typeof DashboardOffersRoute
  DashboardQrHistoryRoute: typeof DashboardQrHistoryRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardRewardsRoute: typeof DashboardRewardsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOffersRoute: DashboardOffersRoute,
  DashboardQrHistoryRoute: DashboardQrHistoryRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardRewardsRoute: DashboardRewardsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DistrictBusinessPartnerRouteChildren {
  DistrictBusinessPartnerSlugRoute: typeof DistrictBusinessPartnerSlugRoute
}

const DistrictBusinessPartnerRouteChildren: DistrictBusinessPartnerRouteChildren =
  {
    DistrictBusinessPartnerSlugRoute: DistrictBusinessPartnerSlugRoute,
  }

const DistrictBusinessPartnerRouteWithChildren =
  DistrictBusinessPartnerRoute._addFileChildren(
    DistrictBusinessPartnerRouteChildren,
  )

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsProfileRoute: typeof JobsProfileRoute
  JobsSearchRoute: typeof JobsSearchRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsProfileRoute: JobsProfileRoute,
  JobsSearchRoute: JobsSearchRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface OwnerJobsRouteChildren {
  OwnerJobsNewRoute: typeof OwnerJobsNewRoute
}

const OwnerJobsRouteChildren: OwnerJobsRouteChildren = {
  OwnerJobsNewRoute: OwnerJobsNewRoute,
}

const OwnerJobsRouteWithChildren = OwnerJobsRoute._addFileChildren(
  OwnerJobsRouteChildren,
)

interface OwnerRouteChildren {
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerCreateWebsiteRoute: typeof OwnerCreateWebsiteRoute
  OwnerCrmRoute: typeof OwnerCrmRoute
  OwnerGalleryRoute: typeof OwnerGalleryRoute
  OwnerJobsRoute: typeof OwnerJobsRouteWithChildren
  OwnerMarketingRoute: typeof OwnerMarketingRoute
  OwnerOnboardingRoute: typeof OwnerOnboardingRoute
  OwnerPaymentsRoute: typeof OwnerPaymentsRoute
  OwnerPendingRoute: typeof OwnerPendingRoute
  OwnerRegisterBusinessRoute: typeof OwnerRegisterBusinessRoute
  OwnerReviewsRoute: typeof OwnerReviewsRoute
  OwnerServicesRoute: typeof OwnerServicesRoute
  OwnerSetupWizardRoute: typeof OwnerSetupWizardRoute
  OwnerStaffRoute: typeof OwnerStaffRoute
  OwnerTemplatesRoute: typeof OwnerTemplatesRoute
  OwnerWebsiteRoute: typeof OwnerWebsiteRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerCreateWebsiteRoute: OwnerCreateWebsiteRoute,
  OwnerCrmRoute: OwnerCrmRoute,
  OwnerGalleryRoute: OwnerGalleryRoute,
  OwnerJobsRoute: OwnerJobsRouteWithChildren,
  OwnerMarketingRoute: OwnerMarketingRoute,
  OwnerOnboardingRoute: OwnerOnboardingRoute,
  OwnerPaymentsRoute: OwnerPaymentsRoute,
  OwnerPendingRoute: OwnerPendingRoute,
  OwnerRegisterBusinessRoute: OwnerRegisterBusinessRoute,
  OwnerReviewsRoute: OwnerReviewsRoute,
  OwnerServicesRoute: OwnerServicesRoute,
  OwnerSetupWizardRoute: OwnerSetupWizardRoute,
  OwnerStaffRoute: OwnerStaffRoute,
  OwnerTemplatesRoute: OwnerTemplatesRoute,
  OwnerWebsiteRoute: OwnerWebsiteRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface PartnerRouteChildren {
  PartnerDistributorRoute: typeof PartnerDistributorRoute
  PartnerDistrictRoute: typeof PartnerDistrictRoute
  PartnerGrowthRoute: typeof PartnerGrowthRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerDistributorRoute: PartnerDistributorRoute,
  PartnerDistrictRoute: PartnerDistrictRoute,
  PartnerGrowthRoute: PartnerGrowthRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DistrictBusinessPartnerRoute: DistrictBusinessPartnerRouteWithChildren,
  ForOwnersRoute: ForOwnersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  OfflineRoute: OfflineRoute,
  OwnerRoute: OwnerRouteWithChildren,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerSignupRoute: OwnerSignupRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookSlugRoute: BookSlugRoute,
  BrandSlugRoute: BrandSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  DistributorSlugRoute: DistributorSlugRoute,
  PortalBusinessPagesRoute: PortalBusinessPagesRoute,
  PortalContactRoute: PortalContactRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLeadsRoute: PortalLeadsRoute,
  PortalPricingRoute: PortalPricingRoute,
  PortalProductsRoute: PortalProductsRoute,
  PortalPromotionsRoute: PortalPromotionsRoute,
  PortalSponsoredRoute: PortalSponsoredRoute,
  SSlugRoute: SSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  SiteBusinessSlugRoute: SiteBusinessSlugRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalBrandsSlugRoute: PortalBrandsSlugRoute,
  PortalBrandsRegisterRoute: PortalBrandsRegisterRoute,
  PortalDistributorsSlugRoute: PortalDistributorsSlugRoute,
  PortalDistributorsRegisterRoute: PortalDistributorsRegisterRoute,
  PortalBrandsIndexRoute: PortalBrandsIndexRoute,
  PortalDistributorsIndexRoute: PortalDistributorsIndexRoute,
  ApiPublicAuthForgotPasswordRoute: ApiPublicAuthForgotPasswordRoute,
  ApiPublicHooksProcessSettlementsRoute: ApiPublicHooksProcessSettlementsRoute,
  ApiPublicHooksRecomputeInsightsRoute: ApiPublicHooksRecomputeInsightsRoute,
  ApiPublicHooksRecomputeRankingsRoute: ApiPublicHooksRecomputeRankingsRoute,
  ApiPublicHooksReleaseExpiredBookingsRoute:
    ApiPublicHooksReleaseExpiredBookingsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
