// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type PublicBackendConfig = {
  supabaseUrl: string;
  supabasePublishableKey: string;
};

function createSupabaseClient() {
  const runtimeConfig = (
    globalThis as typeof globalThis & {
      __NEXORA_BACKEND_CONFIG__?: PublicBackendConfig;
    }
  ).__NEXORA_BACKEND_CONFIG__;

  // Use import.meta.env for client-side (Vite build-time replacement)
  // or the runtime config loaded from the Lovable-managed server. Fall back to
  // process.env for SSR (server-side rendering).
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || runtimeConfig?.supabaseUrl || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    runtimeConfig?.supabasePublishableKey ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  console.log("[Supabase] Client initialized with URL:", SUPABASE_URL);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      console.log("[Supabase] Creating client instance...");
      _supabase = createSupabaseClient();
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
